### PR TITLE
curator date/times are with respect to the curator pod timezone

### PR DESCRIPTION
**Pull request by richm**
@xiazhao2015 @sosiouxme @ewolinetz PTAL

### CODE REVIEW

**Comment by xiazhao2015** [comment]
@richm LGTM, thanks!

**Comment by ewolinetz** [comment]
LGTM -- this also answers my question in https://github.com/openshift/origin-aggregated-logging/issues/182

**Comment by richm** [comment]
@jcantrill timezone is now required

**Comment by richm** [comment]
well . . . looks like the o-a-l testing can't handle checking out submodules of PRs 
I did test this fix locally on top of https://github.com/openshift/origin-integration-common/pull/14/commits/59f4c12ff349abdb8a370f92d8c3c136219d1cc3 
I'd like to get this fix in so we can test with o-a-l

**Pull request merged**
